export const CORE_RECORD_TYPES = [
  ["company", "Société", "Sociétés"],
  ["contact", "Contact", "Contacts"],
  ["lead", "Lead", "Leads"],
  ["opportunity", "Opportunité", "Opportunités"],
  ["task", "Tâche", "Tâches"],
  ["appointment", "Rendez-vous", "Rendez-vous"],
  ["note", "Note", "Notes"],
  ["document", "Document", "Documents (fiches)"],
  ["product", "Produit", "Produits"],
  ["service", "Service", "Services"],
  ["quote", "Devis", "Devis"],
  ["invoice", "Facture", "Factures"],
  ["contract", "Contrat", "Contrats"],
];

const fieldTypes = ["text", "number", "date", "datetime", "boolean", "email", "phone", "currency", "select", "relation", "textarea"];

const commonProcedures = [
  {
    id: "COM-CNX-001",
    version: 1,
    title: "Se connecter à Clarity CRM",
    description: "Ouvrir une session Clarity CRM avec l'authentification existante.",
    roles: ["user", "admin"],
    contexts: ["login", "common"],
    prerequisites: [],
    tags: ["acces", "connexion", "session"],
    steps: [
      { title: "Ouvrir l'application", instruction: "Ouvrir l'URL Clarity CRM fournie par votre administrateur.", expected: "La page de connexion s'affiche." },
      { title: "Saisir l'adresse email", instruction: "Cliquer dans le champ email puis saisir votre adresse professionnelle.", expected: "L'adresse apparaît dans le champ." },
      { title: "Saisir le mot de passe", instruction: "Cliquer dans le champ mot de passe puis saisir votre mot de passe.", expected: "Le champ mot de passe est rempli." },
      { title: "Valider", instruction: "Cliquer sur le bouton de connexion.", expected: "Clarity CRM ouvre l'espace métier réel." },
      { title: "Vérifier la session", instruction: "Contrôler votre nom, votre rôle et l'organisation affichés en haut à droite.", expected: "Le rôle et le tenant correspondent à votre accès." },
    ],
    result: "Vous êtes connecté au tenant autorisé par votre session.",
  },
  {
    id: "COM-CNX-002",
    version: 1,
    title: "Se déconnecter",
    description: "Fermer proprement la session courante.",
    roles: ["user", "admin"],
    contexts: ["common"],
    prerequisites: ["COM-CNX-001"],
    tags: ["acces", "deconnexion", "session"],
    steps: [
      { title: "Repérer la commande", instruction: "En haut ou en bas de l'interface, repérer le bouton de déconnexion disponible dans le shell Clarity CRM.", expected: "Le bouton de déconnexion est visible." },
      { title: "Déconnecter", instruction: "Cliquer sur le bouton de déconnexion.", expected: "La session est révoquée." },
      { title: "Contrôler la sortie", instruction: "Attendre le retour vers l'écran de connexion.", expected: "L'application ne montre plus les données CRM." },
    ],
    result: "Votre session Clarity CRM est fermée.",
  },
  {
    id: "COM-TEN-001",
    version: 1,
    title: "Changer d'organisation",
    description: "Basculer vers un autre tenant autorisé, sans contourner les droits.",
    roles: ["user", "admin"],
    contexts: ["common", "tenant"],
    prerequisites: ["COM-CNX-001"],
    tags: ["tenant", "organisation", "changement"],
    steps: [
      { title: "Ouvrir le sélecteur", instruction: "Repérer le sélecteur d'organisation affiché par Clarity CRM.", expected: "La liste des organisations accessibles s'ouvre." },
      { title: "Choisir l'organisation", instruction: "Cliquer sur l'organisation souhaitée dans la liste.", expected: "Le tenant sélectionné est demandé côté serveur." },
      { title: "Attendre le rechargement", instruction: "Attendre le rechargement de la session.", expected: "Le nom ou l'identifiant du tenant change dans l'en-tête." },
      { title: "Vérifier le périmètre", instruction: "Contrôler que les données affichées correspondent à la nouvelle organisation.", expected: "Les données restent isolées par tenant." },
    ],
    result: "L'organisation courante a changé pour la session active.",
  },
  {
    id: "COM-SRCH-001",
    version: 1,
    title: "Utiliser la recherche globale",
    description: "Rechercher une fiche CRM visible dans votre périmètre.",
    roles: ["user", "admin"],
    contexts: ["crm", "search", "common"],
    permissions: [{ object: "crm_record", action: "read" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["recherche", "crm", "fiche"],
    steps: [
      { title: "Ouvrir CRM universel", instruction: "Dans la navigation gauche, cliquer sur \"CRM universel\".", expected: "La zone Recherche globale apparaît." },
      { title: "Saisir la recherche", instruction: "Cliquer dans le champ \"Au moins 2 caractères\".", expected: "Le curseur est actif dans le champ." },
      { title: "Entrer le texte", instruction: "Saisir au moins deux caractères du titre recherché.", expected: "La valeur est visible dans le champ." },
      { title: "Lancer la recherche", instruction: "Cliquer sur \"Rechercher\".", expected: "Les résultats accessibles s'affichent sous le champ." },
      { title: "Ouvrir un résultat", instruction: "Cliquer sur la ligne correspondant à la fiche souhaitée.", expected: "La fiche est chargée dans le panneau de détail." },
    ],
    result: "Vous avez ouvert une fiche visible selon vos droits et votre scope.",
    troubleshooting: [{ condition: "Aucun résultat", message: "Vérifiez l'orthographe et votre périmètre d'accès.", procedureId: "HELP-ERR-003" }],
  },
  {
    id: "COM-REC-001",
    version: 1,
    title: "Ouvrir une fiche CRM",
    description: "Afficher le détail d'une fiche depuis une liste ou une recherche.",
    roles: ["user", "admin"],
    contexts: ["crm", "record"],
    permissions: [{ object: "crm_record", action: "read" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["fiche", "ouvrir", "crm"],
    steps: [
      { title: "Ouvrir CRM universel", instruction: "Dans la navigation gauche, cliquer sur \"CRM universel\".", expected: "La liste des fiches du type courant apparaît." },
      { title: "Choisir le type", instruction: "Cliquer sur le bouton du type d'objet voulu, par exemple \"Contacts\" ou \"Sociétés\".", expected: "La liste se recharge pour ce type." },
      { title: "Filtrer si besoin", instruction: "Cliquer dans le champ \"Rechercher\" de la liste puis saisir un texte.", expected: "Le filtre est prêt à être appliqué." },
      { title: "Ouvrir la ligne", instruction: "Cliquer sur la ligne de la fiche à consulter.", expected: "Le détail de la fiche s'affiche sous la liste." },
    ],
    result: "La fiche est ouverte avec ses données, son activité, ses documents et ses relations accessibles.",
  },
  {
    id: "COM-AUD-001",
    version: 1,
    title: "Consulter une trace d'audit visible",
    description: "Retrouver les événements visibles dans le dashboard ou les écrans d'activité.",
    roles: ["user", "admin"],
    contexts: ["dashboard", "audit", "common"],
    permissions: [{ object: "audit", action: "read" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["audit", "trace", "historique"],
    steps: [
      { title: "Ouvrir le dashboard", instruction: "Dans la navigation gauche, cliquer sur \"Dashboard\".", expected: "Le dashboard réel s'affiche." },
      { title: "Lire l'activité", instruction: "Dans la carte \"Activité récente\", repérer l'événement à contrôler.", expected: "Les événements autorisés sont listés." },
      { title: "Contrôler la date", instruction: "Lire la date et le type d'événement affichés sur la ligne.", expected: "Vous disposez d'un premier élément de contrôle." },
    ],
    result: "Vous avez consulté les traces visibles selon votre rôle et votre scope.",
  },
];

function recordProcedures() {
  return CORE_RECORD_TYPES.flatMap(([type, singular, plural]) => [
    {
      id: `USR-${type.toUpperCase()}-001`,
      version: 1,
      title: `Créer une fiche ${singular}`,
      description: `Créer un enregistrement ${singular} dans le CRM universel.`,
      roles: ["user", "admin"],
      contexts: ["crm", "record", type],
      permissions: [{ object: type, action: "create" }, { object: "crm_record", action: "create" }],
      recordTypes: [type],
      prerequisites: ["COM-CNX-001"],
      tags: ["crm", "creer", type, singular, plural],
      steps: [
        { title: "Ouvrir CRM universel", instruction: "Dans la navigation gauche, cliquer sur \"CRM universel\".", expected: "La page CRM universel s'affiche." },
        { title: `Choisir ${plural}`, instruction: `Dans la rangée des types d'objets, cliquer sur \"${plural}\".`, expected: `Le titre de liste affiche \"${plural}\".` },
        { title: "Cliquer dans Titre", instruction: "Dans le bloc de création à droite, cliquer dans le champ \"Titre\".", expected: "Le curseur est actif." },
        { title: "Saisir le titre", instruction: `Saisir le titre de la fiche ${singular}.`, expected: "Le titre est visible." },
        { title: "Vérifier le statut", instruction: "Contrôler le champ \"Statut\" et le modifier seulement si nécessaire.", expected: "Le statut souhaité est présent." },
        { title: "Contrôler le JSON", instruction: "Vérifier le contenu du champ \"Données métier JSON\".", expected: "Le JSON reste un objet valide." },
        { title: "Créer", instruction: "Cliquer sur \"Créer l'enregistrement\".", expected: "Un message confirme la création." },
        { title: "Vérifier la liste", instruction: "Contrôler que la fiche apparaît dans la liste des enregistrements visibles.", expected: "La nouvelle fiche est listée si votre scope vous y donne accès." },
      ],
      result: `La fiche ${singular} est créée côté serveur dans le tenant courant.`,
      troubleshooting: [{ condition: "Création refusée", message: "Votre rôle ne possède peut-être pas l'action create sur cet objet.", procedureId: "HELP-ERR-002" }],
    },
    {
      id: `USR-${type.toUpperCase()}-002`,
      version: 1,
      title: `Consulter une fiche ${singular}`,
      description: `Ouvrir et lire une fiche ${singular} accessible.`,
      roles: ["user", "admin"],
      contexts: ["crm", "record", type],
      permissions: [{ object: type, action: "read" }, { object: "crm_record", action: "read" }],
      recordTypes: [type],
      prerequisites: ["COM-REC-001"],
      tags: ["crm", "consulter", type, singular, plural],
      steps: [
        { title: `Choisir ${plural}`, instruction: `Dans \"CRM universel\", cliquer sur \"${plural}\".`, expected: "La liste du type sélectionné s'affiche." },
        { title: "Repérer la fiche", instruction: "Lire la liste ou utiliser le champ \"Rechercher\".", expected: "La fiche souhaitée est visible si elle est dans votre périmètre." },
        { title: "Ouvrir", instruction: "Cliquer sur la ligne de la fiche.", expected: "Le détail s'affiche." },
        { title: "Lire les champs", instruction: "Lire les champs principaux dans le panneau de gauche.", expected: "Les données métier accessibles sont visibles." },
        { title: "Afficher les données avancées", instruction: "Si nécessaire, cliquer sur \"Afficher les données avancées\".", expected: "Le JSON métier complet s'affiche." },
      ],
      result: `La fiche ${singular} est consultée sans modifier les données.`,
    },
    {
      id: `USR-${type.toUpperCase()}-003`,
      version: 1,
      title: `Modifier une fiche ${singular}`,
      description: `Mettre à jour le titre, le statut ou les données JSON d'une fiche ${singular}.`,
      roles: ["user", "admin"],
      contexts: ["crm", "record", "edit", type],
      permissions: [{ object: type, action: "update" }, { object: "crm_record", action: "update" }],
      recordTypes: [type],
      prerequisites: [`USR-${type.toUpperCase()}-002`],
      tags: ["crm", "modifier", type, singular, plural],
      steps: [
        { title: "Ouvrir la fiche", instruction: `Ouvrir la fiche ${singular} à modifier.`, expected: "La zone \"Modifier cette fiche\" est visible." },
        { title: "Cliquer dans Titre", instruction: "Dans \"Modifier cette fiche\", cliquer dans le champ \"Titre\".", expected: "Le titre est modifiable." },
        { title: "Modifier le titre", instruction: "Saisir la nouvelle valeur du titre si nécessaire.", expected: "Le nouveau titre est visible." },
        { title: "Cliquer dans Statut", instruction: "Cliquer dans le champ \"Statut\".", expected: "Le statut est modifiable." },
        { title: "Modifier le JSON", instruction: "Cliquer dans \"Données métier JSON\" et modifier uniquement les clés utiles.", expected: "Le JSON reste valide." },
        { title: "Enregistrer", instruction: "Cliquer sur \"Enregistrer les modifications\".", expected: "Un message confirme la mise à jour." },
      ],
      result: `La fiche ${singular} est mise à jour avec validation serveur et audit.`,
      troubleshooting: [{ condition: "Erreur JSON", message: "Corrigez la syntaxe JSON avant d'enregistrer.", procedureId: "HELP-ERR-006" }],
    },
    {
      id: `USR-${type.toUpperCase()}-004`,
      version: 1,
      title: `Archiver une fiche ${singular}`,
      description: `Archiver une fiche ${singular} lorsque l'action est autorisée.`,
      roles: ["user", "admin"],
      contexts: ["crm", "record", "archive", type],
      permissions: [{ object: type, action: "delete" }, { object: "crm_record", action: "delete" }],
      recordTypes: [type],
      prerequisites: [`USR-${type.toUpperCase()}-002`],
      tags: ["crm", "archiver", type, singular, plural],
      steps: [
        { title: "Ouvrir la fiche", instruction: `Ouvrir la fiche ${singular} à archiver.`, expected: "Le détail de la fiche est visible." },
        { title: "Repérer Archiver", instruction: "Dans le panneau de détail, repérer le bouton \"Archiver\".", expected: "Le bouton est visible si l'interface permet l'action." },
        { title: "Cliquer sur Archiver", instruction: "Cliquer sur \"Archiver\".", expected: "La demande est envoyée côté serveur." },
        { title: "Vérifier la liste", instruction: "Attendre le rechargement puis contrôler que la fiche n'apparaît plus dans les actifs.", expected: "La fiche est retirée de la liste courante." },
      ],
      result: `La fiche ${singular} est archivée si votre permission delete le permet.`,
    },
  ]);
}

const userProcedures = [
  {
    id: "USR-DASH-001",
    version: 1,
    title: "Lire le dashboard",
    description: "Comprendre les indicateurs calculés à partir des données accessibles.",
    roles: ["user", "admin"],
    contexts: ["dashboard"],
    permissions: [{ object: "timeline", action: "read" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["dashboard", "accueil", "indicateurs"],
    steps: [
      { title: "Ouvrir Dashboard", instruction: "Dans la navigation gauche, cliquer sur \"Dashboard\".", expected: "Le dashboard réel s'affiche." },
      { title: "Lire les métriques", instruction: "Lire les cartes \"Opportunités ouvertes\", \"Pipeline ouvert\", \"Tâches ouvertes\" et les autres indicateurs.", expected: "Les chiffres reflètent uniquement votre périmètre." },
      { title: "Lire la répartition", instruction: "Dans \"Répartition du pipeline\", lire les étapes et les compteurs.", expected: "Les étapes visibles sont listées." },
      { title: "Lire l'activité", instruction: "Dans \"Activité récente\", lire les derniers événements visibles.", expected: "Les événements accessibles apparaissent." },
      { title: "Actualiser", instruction: "Cliquer sur \"Actualiser\" pour recharger les métriques.", expected: "Les données sont recalculées." },
    ],
    result: "Vous avez une vue synthétique des données accessibles dans le tenant courant.",
  },
  {
    id: "USR-PAL-001",
    version: 1,
    title: "Utiliser la palette de commande",
    description: "Fonction partielle dans cette version : la recherche globale est disponible dans CRM universel.",
    roles: ["user", "admin"],
    contexts: ["dashboard", "crm", "common"],
    prerequisites: ["COM-CNX-001"],
    tags: ["palette", "commande", "partiel"],
    steps: [
      { title: "Constater la disponibilité", instruction: "Dans cette version, utiliser la zone \"Recherche globale\" de \"CRM universel\".", expected: "La palette dédiée n'est pas exposée dans V1Console." },
      { title: "Ouvrir CRM universel", instruction: "Cliquer sur \"CRM universel\".", expected: "La recherche globale est disponible." },
      { title: "Rechercher", instruction: "Suivre la procédure COM-SRCH-001.", expected: "Les résultats accessibles s'affichent." },
    ],
    result: "La recherche est disponible sans créer de navigation parallèle.",
  },
  {
    id: "USR-PIPE-001",
    version: 1,
    title: "Comprendre le pipeline",
    description: "Lire les opportunités dans les vues disponibles sans inventer un écran pipeline dédié.",
    roles: ["user", "admin"],
    contexts: ["dashboard", "crm", "pipeline", "opportunity"],
    permissions: [{ object: "opportunity", action: "read" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["pipeline", "opportunite", "partiel"],
    steps: [
      { title: "Ouvrir Dashboard", instruction: "Cliquer sur \"Dashboard\".", expected: "La répartition du pipeline est visible." },
      { title: "Lire les étapes", instruction: "Dans \"Répartition du pipeline\", lire les étapes et leurs compteurs.", expected: "Les étapes visibles selon vos droits s'affichent." },
      { title: "Ouvrir CRM universel", instruction: "Cliquer sur \"CRM universel\".", expected: "Les types d'objets s'affichent." },
      { title: "Choisir Opportunités", instruction: "Cliquer sur \"Opportunités\".", expected: "La liste des opportunités accessibles s'affiche." },
      { title: "Ouvrir une opportunité", instruction: "Cliquer sur une opportunité pour lire son statut et ses données métier.", expected: "La fiche opportunité s'affiche." },
    ],
    result: "Le pipeline est consulté via les indicateurs et l'objet Opportunité réellement disponible.",
  },
  {
    id: "USR-DOC-001",
    version: 1,
    title: "Ajouter un document à une fiche",
    description: "Téléverser un document lié à une fiche ouverte.",
    roles: ["user", "admin"],
    contexts: ["crm", "documents", "record"],
    permissions: [{ object: "document", action: "create" }, { object: "crm_record", action: "update" }],
    prerequisites: ["COM-REC-001"],
    tags: ["document", "televerser", "fiche"],
    steps: [
      { title: "Ouvrir une fiche", instruction: "Dans \"CRM universel\", ouvrir la fiche qui doit recevoir le document.", expected: "Le panneau \"Documents liés\" est visible." },
      { title: "Choisir le fichier", instruction: "Dans \"Documents liés\", cliquer sur le champ de fichier.", expected: "Le sélecteur de fichiers du navigateur s'ouvre." },
      { title: "Sélectionner", instruction: "Sélectionner un fichier autorisé puis valider.", expected: "Le téléversement démarre." },
      { title: "Vérifier", instruction: "Attendre l'apparition du document dans la liste.", expected: "Le document apparaît avec son nom et sa taille." },
    ],
    result: "Le document est lié à la fiche dans le tenant courant.",
  },
  {
    id: "USR-DOC-002",
    version: 1,
    title: "Télécharger un document lié",
    description: "Télécharger un document accessible depuis une fiche.",
    roles: ["user", "admin"],
    contexts: ["crm", "documents", "record"],
    permissions: [{ object: "document", action: "read" }, { object: "crm_record", action: "read" }],
    prerequisites: ["COM-REC-001"],
    tags: ["document", "telecharger", "fiche"],
    steps: [
      { title: "Ouvrir la fiche", instruction: "Ouvrir la fiche qui contient le document.", expected: "La liste \"Documents liés\" est visible." },
      { title: "Repérer le document", instruction: "Lire la liste des documents et repérer le fichier souhaité.", expected: "Le nom du fichier est visible." },
      { title: "Télécharger", instruction: "Cliquer sur le nom du document.", expected: "Le téléchargement démarre via l'API documents." },
    ],
    result: "Le document est téléchargé si vos droits autorisent la lecture.",
  },
  {
    id: "USR-DOC-003",
    version: 1,
    title: "Archiver un document lié",
    description: "Archiver un document depuis une fiche ouverte.",
    roles: ["user", "admin"],
    contexts: ["crm", "documents", "record"],
    permissions: [{ object: "document", action: "delete" }, { object: "crm_record", action: "update" }],
    prerequisites: ["USR-DOC-002"],
    tags: ["document", "archiver", "fiche"],
    steps: [
      { title: "Ouvrir la fiche", instruction: "Ouvrir la fiche qui contient le document.", expected: "Les documents liés sont visibles." },
      { title: "Repérer Archiver", instruction: "Sur la ligne du document, repérer le bouton \"Archiver\".", expected: "Le bouton est visible." },
      { title: "Cliquer Archiver", instruction: "Cliquer sur \"Archiver\".", expected: "Le document disparaît de la liste active." },
    ],
    result: "Le document est archivé côté serveur.",
  },
  {
    id: "USR-REL-001",
    version: 1,
    title: "Ajouter une relation entre deux fiches",
    description: "Créer une relation entre la fiche ouverte et une autre fiche du tenant.",
    roles: ["user", "admin"],
    contexts: ["crm", "relations", "record"],
    permissions: [{ object: "crm_relation", action: "create" }],
    prerequisites: ["COM-REC-001"],
    tags: ["relation", "fiche", "lier"],
    steps: [
      { title: "Ouvrir la fiche source", instruction: "Ouvrir la fiche qui portera la relation.", expected: "Le bloc \"Relations\" est visible." },
      { title: "Cliquer dans l'ID", instruction: "Dans \"Relations\", cliquer dans le champ \"ID de la fiche liée\".", expected: "Le curseur est actif." },
      { title: "Saisir l'ID", instruction: "Coller l'identifiant de la fiche cible.", expected: "L'ID est présent." },
      { title: "Saisir le type", instruction: "Cliquer dans le champ du type de relation et saisir par exemple \"related_to\".", expected: "Le type est présent." },
      { title: "Lier", instruction: "Cliquer sur \"Lier\".", expected: "La relation apparaît dans la liste." },
    ],
    result: "La relation est créée si les deux fiches appartiennent au même tenant et sont autorisées.",
  },
  {
    id: "USR-REL-002",
    version: 1,
    title: "Ouvrir une fiche liée",
    description: "Naviguer depuis une relation vers la fiche associée.",
    roles: ["user", "admin"],
    contexts: ["crm", "relations", "record"],
    permissions: [{ object: "crm_relation", action: "read" }, { object: "crm_record", action: "read" }],
    prerequisites: ["COM-REC-001"],
    tags: ["relation", "ouvrir", "fiche"],
    steps: [
      { title: "Ouvrir la fiche source", instruction: "Ouvrir une fiche qui possède des relations.", expected: "La liste des relations est visible." },
      { title: "Choisir la relation", instruction: "Repérer la fiche liée souhaitée dans le bloc \"Relations\".", expected: "Le titre de la fiche liée est visible." },
      { title: "Ouvrir", instruction: "Cliquer sur le titre de la fiche liée.", expected: "La fiche liée s'ouvre dans le panneau de détail." },
    ],
    result: "La fiche liée est ouverte si elle est accessible dans votre scope.",
  },
  {
    id: "USR-REL-003",
    version: 1,
    title: "Supprimer une relation",
    description: "Retirer le lien entre deux fiches lorsque l'action est disponible.",
    roles: ["user", "admin"],
    contexts: ["crm", "relations", "record"],
    permissions: [{ object: "crm_relation", action: "delete" }],
    prerequisites: ["USR-REL-002"],
    tags: ["relation", "supprimer", "fiche"],
    steps: [
      { title: "Ouvrir la fiche source", instruction: "Ouvrir la fiche qui contient la relation à supprimer.", expected: "Le bloc \"Relations\" est visible." },
      { title: "Repérer la relation", instruction: "Repérer la ligne de relation à retirer.", expected: "Le bouton \"Supprimer\" est visible." },
      { title: "Supprimer", instruction: "Cliquer sur \"Supprimer\".", expected: "La relation disparaît de la liste." },
    ],
    result: "La relation est supprimée, sans supprimer les fiches elles-mêmes.",
  },
  {
    id: "USR-TIME-001",
    version: 1,
    title: "Consulter la timeline d'une fiche",
    description: "Lire les événements rattachés à une fiche.",
    roles: ["user", "admin"],
    contexts: ["crm", "timeline", "record"],
    permissions: [{ object: "timeline", action: "read" }],
    prerequisites: ["COM-REC-001"],
    tags: ["timeline", "activite", "fiche"],
    steps: [
      { title: "Ouvrir la fiche", instruction: "Ouvrir la fiche à contrôler.", expected: "Le bloc \"Activité\" est visible." },
      { title: "Lire les événements", instruction: "Dans \"Activité\", lire les lignes affichées.", expected: "Chaque événement affiche un résumé et une date." },
      { title: "Contrôler l'absence", instruction: "Si aucune ligne n'apparaît, lire le message affiché.", expected: "L'interface indique qu'aucune activité n'est visible pour le moment." },
    ],
    result: "La timeline visible est consultée sans modification.",
  },
  {
    id: "USR-TIME-002",
    version: 1,
    title: "Ajouter une activité à la timeline",
    description: "Interface non disponible dans cette version.",
    roles: ["user", "admin"],
    contexts: ["crm", "timeline", "record"],
    permissions: [{ object: "timeline", action: "create" }],
    prerequisites: ["COM-REC-001"],
    tags: ["timeline", "partiel"],
    steps: [
      { title: "Constater la disponibilité", instruction: "Ouvrir une fiche et regarder le bloc \"Activité\".", expected: "La timeline est consultable." },
      { title: "Vérifier l'action", instruction: "Chercher un bouton d'ajout d'activité dans ce bloc.", expected: "Aucun bouton d'ajout n'est exposé dans V1Console." },
    ],
    result: "L'ajout manuel d'activité n'est pas exposé par l'interface actuelle.",
  },
  {
    id: "USR-NOTIF-001",
    version: 1,
    title: "Consulter les notifications",
    description: "Lire les notifications internes liées au tenant et au destinataire.",
    roles: ["user", "admin"],
    contexts: ["notifications"],
    prerequisites: ["COM-CNX-001"],
    tags: ["notification", "lire"],
    steps: [
      { title: "Ouvrir Notifications", instruction: "Dans la navigation gauche, cliquer sur \"Notifications\".", expected: "La page Notifications internes s'affiche." },
      { title: "Lire le compteur", instruction: "Lire le nombre de notifications non lues sous le titre.", expected: "Le compteur est visible." },
      { title: "Lire une notification", instruction: "Lire le message et la date sur la ligne souhaitée.", expected: "Le détail de base est visible." },
    ],
    result: "Les notifications visibles sont consultées.",
  },
  {
    id: "USR-NOTIF-002",
    version: 1,
    title: "Ouvrir la ressource d'une notification",
    description: "Accéder à la fiche liée à une notification.",
    roles: ["user", "admin"],
    contexts: ["notifications", "crm"],
    prerequisites: ["USR-NOTIF-001"],
    tags: ["notification", "ressource"],
    steps: [
      { title: "Ouvrir Notifications", instruction: "Cliquer sur \"Notifications\".", expected: "Les notifications s'affichent." },
      { title: "Repérer le lien", instruction: "Sur une notification contenant une ressource, repérer \"Voir la ressource liée\".", expected: "Le lien est visible si une ressource est attachée." },
      { title: "Ouvrir", instruction: "Cliquer sur \"Voir la ressource liée\".", expected: "Clarity CRM ouvre la fiche concernée dans CRM universel." },
    ],
    result: "La ressource liée est ouverte si elle est encore accessible.",
  },
  {
    id: "USR-NOTIF-003",
    version: 1,
    title: "Marquer une notification comme lue",
    description: "Passer une notification non lue en état lu.",
    roles: ["user", "admin"],
    contexts: ["notifications"],
    prerequisites: ["USR-NOTIF-001"],
    tags: ["notification", "lu"],
    steps: [
      { title: "Ouvrir Notifications", instruction: "Cliquer sur \"Notifications\".", expected: "Les notifications internes s'affichent." },
      { title: "Repérer l'action", instruction: "Sur une notification non lue, repérer \"Marquer lue\".", expected: "Le bouton est visible." },
      { title: "Marquer", instruction: "Cliquer sur \"Marquer lue\".", expected: "Le statut de la notification passe à \"Lu\"." },
    ],
    result: "La notification est marquée comme lue pour votre utilisateur.",
  },
  {
    id: "USR-IMP-001",
    version: 1,
    title: "Importer un CSV",
    description: "Prévisualiser puis confirmer un import CSV pour le type courant.",
    roles: ["user", "admin"],
    contexts: ["crm", "import"],
    permissions: [{ object: "crm_record", action: "create" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["import", "csv", "crm"],
    steps: [
      { title: "Ouvrir CRM universel", instruction: "Cliquer sur \"CRM universel\".", expected: "La zone d'import CSV contrôlé est visible." },
      { title: "Choisir le type", instruction: "Cliquer sur le type d'objet à importer.", expected: "Le type courant est sélectionné." },
      { title: "Choisir le fichier", instruction: "Dans \"Import CSV contrôlé\", cliquer sur le champ fichier.", expected: "Le sélecteur de fichiers s'ouvre." },
      { title: "Sélectionner le CSV", instruction: "Sélectionner un fichier CSV UTF-8.", expected: "Le fichier est attaché." },
      { title: "Prévisualiser", instruction: "Cliquer sur \"Prévisualiser\".", expected: "Un rapport de prévisualisation JSON s'affiche." },
      { title: "Confirmer", instruction: "Cliquer sur \"Confirmer l'import\" seulement après contrôle du rapport.", expected: "L'import est exécuté côté serveur." },
    ],
    result: "Le CSV est importé après prévisualisation obligatoire.",
    troubleshooting: [{ condition: "Import refusé", message: "Consultez le rapport et les permissions create.", procedureId: "HELP-ERR-004" }],
  },
  {
    id: "USR-EXP-001",
    version: 1,
    title: "Exporter en CSV ou Excel",
    description: "Exporter les enregistrements visibles selon les permissions.",
    roles: ["user", "admin"],
    contexts: ["crm", "export"],
    permissions: [{ object: "crm_record", action: "export" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["export", "csv", "xlsx"],
    steps: [
      { title: "Ouvrir CRM universel", instruction: "Cliquer sur \"CRM universel\".", expected: "Le bloc \"Export contrôlé\" est visible." },
      { title: "Choisir le type", instruction: "Cliquer sur le type d'objet à exporter.", expected: "Le type courant est sélectionné." },
      { title: "Exporter CSV", instruction: "Cliquer sur \"CSV UTF-8\" pour télécharger un CSV.", expected: "Le téléchargement CSV démarre." },
      { title: "Exporter Excel", instruction: "Cliquer sur \"Excel (.xlsx)\" si vous souhaitez un fichier XLSX.", expected: "Le téléchargement Excel démarre si autorisé." },
    ],
    result: "L'export contient uniquement les données visibles selon RBAC et scopes.",
  },
];

const adminProcedures = [
  {
    id: "ADM-ACC-001",
    version: 1,
    title: "Ouvrir la zone Configuration",
    description: "Accéder aux fonctions d'administration exposées dans V1Console.",
    roles: ["admin"],
    contexts: ["config", "admin"],
    permissions: [{ object: "crm_configuration", action: "administer" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["admin", "configuration", "acces"],
    steps: [
      { title: "Vérifier le rôle", instruction: "Contrôler en haut à droite que votre rôle est \"admin\".", expected: "Le rôle admin est affiché." },
      { title: "Ouvrir Configuration", instruction: "Dans la navigation gauche, cliquer sur \"Configuration\".", expected: "Le studio de configuration s'affiche." },
      { title: "Vérifier les actions", instruction: "Contrôler que le formulaire \"Nouvelle configuration\" est visible.", expected: "Les actions d'administration sont disponibles." },
    ],
    result: "La zone Configuration est ouverte avec les actions autorisées.",
  },
  {
    id: "ADM-USR-001",
    version: 1,
    title: "Inviter un utilisateur",
    description: "Créer une invitation depuis l'interface Droits & équipes lorsque le shell avancé est actif.",
    roles: ["admin"],
    contexts: ["rights", "admin"],
    permissions: [{ object: "admin", action: "administer" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["admin", "utilisateur", "invitation", "partiel"],
    steps: [
      { title: "Constater l'interface", instruction: "Dans cette version active, V1Console n'expose pas l'écran \"Droits & équipes\".", expected: "La navigation affiche Dashboard, CRM universel, Formulaires, Configuration, Automatisations, Webhooks, Notifications." },
      { title: "Utiliser le shell avancé si disponible", instruction: "Si votre déploiement utilise le shell avancé, cliquer dans la barre latérale gauche sur \"Droits & équipes\".", expected: "La page Droits & équipes s'affiche." },
      { title: "Ouvrir Invitations", instruction: "Repérer la section \"Inviter un utilisateur\".", expected: "Les champs email, rôle et équipe sont visibles." },
      { title: "Saisir l'email", instruction: "Cliquer dans le champ \"email@societe.fr\" puis saisir l'adresse email.", expected: "L'adresse est visible." },
      { title: "Choisir le rôle", instruction: "Cliquer sur le sélecteur de rôle puis choisir \"Utilisateur\" ou \"Administrateur\".", expected: "Le rôle choisi est affiché." },
      { title: "Choisir l'équipe", instruction: "Cliquer sur le sélecteur d'équipe puis choisir l'équipe adaptée.", expected: "L'équipe choisie est affichée." },
      { title: "Envoyer", instruction: "Cliquer sur \"Enregistrer l'invitation\".", expected: "L'invitation apparaît dans la liste." },
    ],
    result: "L'invitation est créée si l'écran Droits & équipes est exposé sur votre déploiement.",
  },
  {
    id: "ADM-TEAM-001",
    version: 1,
    title: "Créer une équipe",
    description: "Créer une équipe depuis Droits & équipes lorsque l'écran est disponible.",
    roles: ["admin"],
    contexts: ["rights", "admin"],
    permissions: [{ object: "admin", action: "administer" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["admin", "equipe", "partiel"],
    steps: [
      { title: "Ouvrir Droits & équipes", instruction: "Si le shell avancé est actif, cliquer sur \"Droits & équipes\".", expected: "La section \"Équipes\" s'affiche." },
      { title: "Saisir le nom", instruction: "Cliquer dans le champ \"Nouvelle équipe\" puis saisir le nom.", expected: "Le nom est visible." },
      { title: "Créer", instruction: "Cliquer sur le bouton avec le symbole plus.", expected: "L'équipe apparaît dans la liste." },
    ],
    result: "L'équipe est créée côté serveur si l'écran est exposé.",
  },
  {
    id: "ADM-RBAC-001",
    version: 1,
    title: "Comprendre et modifier une permission",
    description: "Documenter les scopes personal, team et tenant sans créer de contournement.",
    roles: ["admin"],
    contexts: ["rights", "admin", "rbac"],
    permissions: [{ object: "admin", action: "administer" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["admin", "rbac", "permission", "scope"],
    steps: [
      { title: "Ouvrir Droits & équipes", instruction: "Si l'écran est disponible, cliquer sur \"Droits & équipes\".", expected: "La table \"Permissions persistantes\" s'affiche." },
      { title: "Choisir le profil", instruction: "Repérer la ligne du profil \"Administrateur\" ou \"Utilisateur\".", expected: "Le profil est visible." },
      { title: "Lire l'objet", instruction: "Lire la colonne \"Objet\" pour savoir quelle ressource est concernée.", expected: "L'objet est identifié." },
      { title: "Lire l'action", instruction: "Lire la colonne \"Action\" : read, create, update, delete, export ou administer.", expected: "L'action est identifiée." },
      { title: "Choisir le scope", instruction: "Cliquer sur le sélecteur \"Périmètre\" puis choisir \"Personnel\", \"Équipe\" ou \"Tenant\".", expected: "Le nouveau scope est envoyé au serveur." },
      { title: "Comprendre personal", instruction: "\"Personnel\" limite l'accès aux ressources dont l'utilisateur est propriétaire.", expected: "Le scope est compris." },
      { title: "Comprendre team", instruction: "\"Équipe\" limite l'accès aux ressources de l'équipe de l'utilisateur.", expected: "Le scope est compris." },
      { title: "Comprendre tenant", instruction: "\"Tenant\" donne l'accès à l'ensemble de l'organisation courante pour cette permission.", expected: "Le scope est compris." },
    ],
    result: "La permission reste stockée et appliquée côté serveur.",
  },
  {
    id: "ADM-FORM-001",
    version: 1,
    title: "Créer un formulaire configuré",
    description: "Créer une configuration de formulaire depuis le studio de configuration.",
    roles: ["admin"],
    contexts: ["config", "forms", "admin"],
    permissions: [{ object: "crm_configuration", action: "administer" }],
    prerequisites: ["ADM-ACC-001"],
    tags: ["admin", "formulaire", "configuration"],
    steps: [
      { title: "Ouvrir Configuration", instruction: "Dans la navigation gauche, cliquer sur \"Configuration\".", expected: "Le studio de configuration s'affiche." },
      { title: "Choisir le type", instruction: "Dans \"Nouvelle configuration\", cliquer sur le champ \"Type\".", expected: "La liste des types s'ouvre." },
      { title: "Sélectionner form", instruction: "Choisir \"form\".", expected: "Un exemple de définition formulaire est chargé." },
      { title: "Saisir le nom", instruction: "Cliquer dans \"Nom\" puis saisir le nom du formulaire.", expected: "Le nom est visible." },
      { title: "Modifier la clé", instruction: "Dans \"Définition avancée (JSON)\", renseigner une clé en minuscules, chiffres, tirets ou underscores.", expected: "La clé respecte les règles serveur." },
      { title: "Ajouter un champ", instruction: `Dans le tableau JSON \"fields\", ajouter un champ avec un type supporté : ${fieldTypes.join(", ")}.`, expected: "Le JSON reste valide." },
      { title: "Rendre obligatoire", instruction: "Ajouter ou modifier \"required\": true sur le champ concerné.", expected: "Le champ est marqué obligatoire." },
      { title: "Enregistrer", instruction: "Cliquer sur \"Créer et versionner\".", expected: "La configuration est créée et versionnée." },
    ],
    result: "Le formulaire est publié comme configuration active si la validation serveur réussit.",
  },
  {
    id: "ADM-CONF-001",
    version: 1,
    title: "Créer une configuration",
    description: "Créer une configuration versionnée pour objet, pipeline, module, template, automation ou webhook.",
    roles: ["admin"],
    contexts: ["config", "admin"],
    permissions: [{ object: "crm_configuration", action: "administer" }],
    prerequisites: ["ADM-ACC-001"],
    tags: ["admin", "configuration", "version"],
    steps: [
      { title: "Ouvrir Configuration", instruction: "Cliquer sur \"Configuration\".", expected: "Le studio de configuration s'affiche." },
      { title: "Choisir Type", instruction: "Cliquer sur le champ \"Type\" puis choisir le type adapté.", expected: "Un exemple JSON est chargé." },
      { title: "Saisir Nom", instruction: "Cliquer dans \"Nom\" puis saisir un nom clair.", expected: "Le nom est visible." },
      { title: "Éditer JSON", instruction: "Modifier la définition dans \"Définition avancée (JSON)\".", expected: "Le JSON reste un objet valide." },
      { title: "Créer", instruction: "Cliquer sur \"Créer et versionner\".", expected: "La configuration apparaît dans la liste." },
    ],
    result: "La configuration est créée avec une version initiale.",
  },
  {
    id: "ADM-CONF-002",
    version: 1,
    title: "Consulter l'historique et restaurer une configuration",
    description: "Ouvrir les versions d'une configuration et restaurer une version disponible.",
    roles: ["admin"],
    contexts: ["config", "admin"],
    permissions: [{ object: "crm_configuration", action: "administer" }],
    prerequisites: ["ADM-ACC-001"],
    tags: ["admin", "configuration", "historique", "restauration"],
    steps: [
      { title: "Ouvrir Configuration", instruction: "Cliquer sur \"Configuration\".", expected: "Les configurations sont listées." },
      { title: "Ouvrir historique", instruction: "Sur une configuration, cliquer sur \"Historique et restauration\".", expected: "Les versions se chargent." },
      { title: "Choisir une version", instruction: "Repérer la version à restaurer.", expected: "Le bouton \"Restaurer\" est visible si ce n'est pas la version courante." },
      { title: "Restaurer", instruction: "Cliquer sur \"Restaurer\".", expected: "Un message confirme la restauration." },
      { title: "Vérifier", instruction: "Contrôler que la version courante a changé.", expected: "La configuration est rechargée." },
    ],
    result: "La configuration est restaurée via le mécanisme serveur versionné.",
  },
  {
    id: "ADM-AUTO-001",
    version: 1,
    title: "Créer une automatisation",
    description: "Créer une automatisation comme configuration versionnée.",
    roles: ["admin"],
    contexts: ["automations", "config", "admin"],
    permissions: [{ object: "automation", action: "administer" }, { object: "crm_configuration", action: "administer" }],
    prerequisites: ["ADM-CONF-001"],
    tags: ["admin", "automatisation", "workflow"],
    steps: [
      { title: "Ouvrir Configuration", instruction: "Cliquer sur \"Configuration\".", expected: "Le formulaire \"Nouvelle configuration\" est visible." },
      { title: "Choisir automation", instruction: "Dans \"Type\", choisir \"automation\".", expected: "Un modèle d'automatisation est chargé." },
      { title: "Nommer", instruction: "Cliquer dans \"Nom\" puis saisir le nom de la règle.", expected: "Le nom est visible." },
      { title: "Choisir événement", instruction: "Dans le JSON, renseigner trigger.event avec un événement supporté, par exemple \"record.created\".", expected: "Le déclencheur est défini." },
      { title: "Ajouter condition", instruction: "Dans le JSON, compléter le tableau \"conditions\" si une condition est nécessaire.", expected: "Les conditions sont définies." },
      { title: "Choisir action", instruction: "Dans le JSON, compléter le tableau \"actions\" avec l'action souhaitée.", expected: "L'action est définie." },
      { title: "Créer", instruction: "Cliquer sur \"Créer et versionner\".", expected: "L'automatisation apparaît dans Configuration et Automatisations." },
    ],
    result: "L'automatisation est créée sans moteur parallèle.",
  },
  {
    id: "ADM-AUTO-002",
    version: 1,
    title: "Activer ou désactiver une automatisation",
    description: "Basculer l'état actif d'une automatisation existante.",
    roles: ["admin"],
    contexts: ["automations"],
    permissions: [{ object: "automation", action: "administer" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["admin", "automatisation", "activer"],
    steps: [
      { title: "Ouvrir Automatisations", instruction: "Dans la navigation gauche, cliquer sur \"Automatisations\".", expected: "Le workflow builder s'affiche." },
      { title: "Repérer la règle", instruction: "Repérer l'automatisation à modifier dans la liste.", expected: "La carte de la règle est visible." },
      { title: "Basculer", instruction: "Cliquer sur le bouton \"Actif · désactiver\" ou \"Inactif · activer\".", expected: "Le statut change côté serveur." },
      { title: "Vérifier", instruction: "Contrôler le message de confirmation et le nouvel état affiché.", expected: "L'état correspond à l'action demandée." },
    ],
    result: "L'automatisation est activée ou désactivée via les configurations existantes.",
  },
  {
    id: "ADM-AUTO-003",
    version: 1,
    title: "Consulter les runs d'automatisation",
    description: "Lire le journal d'exécution des automatisations.",
    roles: ["admin"],
    contexts: ["automations"],
    permissions: [{ object: "automation", action: "read" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["admin", "automatisation", "runs"],
    steps: [
      { title: "Ouvrir Automatisations", instruction: "Cliquer sur \"Automatisations\".", expected: "Le workflow builder s'affiche." },
      { title: "Lire Exécutions réelles", instruction: "Dans le panneau droit, lire le bloc \"Exécutions réelles\".", expected: "Les runs accessibles sont affichés en JSON." },
      { title: "Contrôler la règle", instruction: "Comparer les informations du run avec la règle concernée.", expected: "Le run est analysable." },
    ],
    result: "Les exécutions sont consultées dans le tenant courant.",
  },
  {
    id: "ADM-WEB-001",
    version: 1,
    title: "Créer un webhook",
    description: "Créer un webhook via une configuration versionnée.",
    roles: ["admin"],
    contexts: ["webhooks", "config", "admin"],
    permissions: [{ object: "webhook", action: "administer" }, { object: "crm_configuration", action: "administer" }],
    prerequisites: ["ADM-CONF-001"],
    tags: ["admin", "webhook", "configuration", "ssrf"],
    steps: [
      { title: "Ouvrir Configuration", instruction: "Cliquer sur \"Configuration\".", expected: "Le studio de configuration s'affiche." },
      { title: "Choisir webhook", instruction: "Dans \"Type\", choisir \"webhook\".", expected: "Un modèle webhook est chargé." },
      { title: "Nommer", instruction: "Cliquer dans \"Nom\" puis saisir le nom du webhook.", expected: "Le nom est visible." },
      { title: "Saisir URL", instruction: "Dans le JSON, renseigner \"url\" avec l'URL HTTPS autorisée.", expected: "L'URL est présente." },
      { title: "Choisir événement", instruction: "Dans le JSON, renseigner \"event\" avec l'événement à livrer.", expected: "L'événement est défini." },
      { title: "Créer", instruction: "Cliquer sur \"Créer et versionner\".", expected: "Le webhook est créé si la politique de sécurité l'autorise." },
    ],
    result: "Le webhook est créé avec validation serveur. Aucune méthode de contournement SSRF n'est documentée.",
    troubleshooting: [{ condition: "Webhook refusé", message: "Contrôlez l'URL et la politique de sécurité.", procedureId: "HELP-ERR-005" }],
  },
  {
    id: "ADM-WEB-002",
    version: 1,
    title: "Consulter les livraisons webhook",
    description: "Lire les livraisons webhook journalisées.",
    roles: ["admin"],
    contexts: ["webhooks"],
    permissions: [{ object: "webhook", action: "read" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["admin", "webhook", "livraison"],
    steps: [
      { title: "Ouvrir Webhooks", instruction: "Dans la navigation gauche, cliquer sur \"Webhooks\".", expected: "La page Livraisons webhook s'affiche." },
      { title: "Lire le journal", instruction: "Lire le JSON affiché dans le panneau.", expected: "Les livraisons accessibles apparaissent." },
      { title: "Identifier l'échec", instruction: "Repérer les statuts ou messages d'erreur dans la livraison.", expected: "L'échec est analysable sans action risquée." },
    ],
    result: "Les livraisons webhook sont consultées.",
  },
  {
    id: "ADM-AUD-001",
    version: 1,
    title: "Analyser un refus d'accès",
    description: "Utiliser les messages et traces visibles pour comprendre un refus.",
    roles: ["admin"],
    contexts: ["audit", "dashboard", "admin"],
    permissions: [{ object: "audit", action: "read" }],
    prerequisites: ["COM-AUD-001"],
    tags: ["admin", "audit", "refus"],
    steps: [
      { title: "Lire le message utilisateur", instruction: "Demander à l'utilisateur le message affiché, par exemple \"Autorisation insuffisante\".", expected: "Le symptôme est connu." },
      { title: "Contrôler le rôle", instruction: "Vérifier le rôle affiché en haut à droite sur la session de l'utilisateur.", expected: "Le rôle réel est identifié." },
      { title: "Contrôler l'objet", instruction: "Identifier l'objet et l'action concernée : read, create, update, delete, export ou administer.", expected: "La permission attendue est connue." },
      { title: "Contrôler le scope", instruction: "Comparer personal, team ou tenant avec la ressource ciblée.", expected: "La cause probable est identifiée." },
    ],
    result: "Le refus est analysé sans contourner le RBAC.",
  },
  {
    id: "ADM-DATA-001",
    version: 1,
    title: "Administrer import et export",
    description: "Utiliser les fonctions d'intégration réellement exposées.",
    roles: ["admin"],
    contexts: ["crm", "data", "admin"],
    permissions: [{ object: "crm_record", action: "export" }, { object: "crm_record", action: "create" }],
    prerequisites: ["COM-CNX-001"],
    tags: ["admin", "donnees", "api", "import", "export"],
    steps: [
      { title: "Ouvrir CRM universel", instruction: "Cliquer sur \"CRM universel\".", expected: "Les blocs import et export sont visibles." },
      { title: "Choisir un objet", instruction: "Cliquer sur le type d'objet concerné.", expected: "Le type courant change." },
      { title: "Importer", instruction: "Pour importer, suivre USR-IMP-001.", expected: "L'import est prévisualisé puis confirmé." },
      { title: "Exporter", instruction: "Pour exporter, suivre USR-EXP-001.", expected: "Le téléchargement respecte les permissions." },
      { title: "API", instruction: "Pour l'API, utiliser uniquement les routes exposées par le déploiement et les permissions serveur.", expected: "Aucun accès hors tenant n'est accordé." },
    ],
    result: "Les données sont intégrées par les APIs existantes et les contrôles serveur.",
  },
];

const troubleshootingProcedures = [
  {
    id: "HELP-ERR-001",
    version: 1,
    title: "Je ne vois pas une fonction",
    description: "Comprendre pourquoi une fonction n'est pas visible.",
    roles: ["user", "admin"],
    contexts: ["troubleshooting", "common"],
    prerequisites: ["COM-CNX-001"],
    tags: ["depannage", "fonction", "visible"],
    steps: [
      { title: "Vérifier le rôle", instruction: "Regarder en haut à droite si votre session indique \"user\" ou \"admin\".", expected: "Le rôle réel est identifié." },
      { title: "Vérifier la page", instruction: "Contrôler que vous êtes sur la bonne page de navigation.", expected: "Le contexte est confirmé." },
      { title: "Vérifier la permission", instruction: "Si l'action concerne une création, modification, suppression ou export, demander à un administrateur de contrôler la permission.", expected: "La permission manquante est identifiée." },
      { title: "Vérifier la disponibilité", instruction: "Lire la procédure liée : certaines fonctions sont indiquées comme partiellement exposées.", expected: "Vous savez si l'interface existe dans cette version." },
    ],
    result: "La cause probable est un rôle, une permission, un scope ou une interface non disponible.",
  },
  {
    id: "HELP-ERR-002",
    version: 1,
    title: "Accès refusé",
    description: "Traiter un refus sans contourner la sécurité.",
    roles: ["user", "admin"],
    contexts: ["troubleshooting", "permissions"],
    prerequisites: ["COM-CNX-001"],
    tags: ["depannage", "403", "rbac", "permission"],
    steps: [
      { title: "Lire le message", instruction: "Lire exactement le message affiché par Clarity CRM.", expected: "Le message est connu." },
      { title: "Identifier l'action", instruction: "Noter l'action tentée : lecture, création, modification, suppression, export ou administration.", expected: "L'action est connue." },
      { title: "Identifier l'objet", instruction: "Noter l'objet concerné : contact, société, opportunité, document, relation, etc.", expected: "L'objet est connu." },
      { title: "Contacter un administrateur", instruction: "Demander le contrôle du rôle, du scope et de la permission côté serveur.", expected: "Aucun contournement n'est tenté." },
    ],
    result: "Le refus est traité comme un contrôle de sécurité normal.",
  },
  {
    id: "HELP-ERR-003",
    version: 1,
    title: "Je ne retrouve pas une fiche",
    description: "Chercher une fiche sans supposer un problème technique.",
    roles: ["user", "admin"],
    contexts: ["troubleshooting", "crm", "search"],
    prerequisites: ["COM-SRCH-001"],
    tags: ["depannage", "recherche", "fiche"],
    steps: [
      { title: "Vérifier le type", instruction: "Dans CRM universel, cliquer sur le bon type d'objet.", expected: "Le type recherché est sélectionné." },
      { title: "Simplifier la recherche", instruction: "Saisir seulement deux ou trois caractères distinctifs.", expected: "La recherche est moins restrictive." },
      { title: "Contrôler le statut", instruction: "Demander si la fiche a été archivée.", expected: "L'hypothèse d'archivage est vérifiée." },
      { title: "Contrôler le scope", instruction: "Demander à un administrateur si votre scope est personal, team ou tenant.", expected: "Le périmètre d'accès est compris." },
    ],
    result: "Vous savez si la fiche est absente, archivée ou hors périmètre.",
  },
  {
    id: "HELP-ERR-004",
    version: 1,
    title: "Un import échoue",
    description: "Diagnostiquer un import CSV échoué depuis l'interface.",
    roles: ["user", "admin"],
    contexts: ["troubleshooting", "import"],
    prerequisites: ["USR-IMP-001"],
    tags: ["depannage", "import", "csv"],
    steps: [
      { title: "Lire le rapport", instruction: "Après \"Prévisualiser\", lire le rapport JSON affiché.", expected: "Les erreurs de lignes ou de format sont visibles." },
      { title: "Vérifier le type", instruction: "Contrôler que le type d'objet sélectionné correspond au fichier.", expected: "Le type est cohérent." },
      { title: "Vérifier l'encodage", instruction: "Contrôler que le fichier est un CSV UTF-8.", expected: "Le format est compatible." },
      { title: "Vérifier les permissions", instruction: "Si l'import est refusé, demander le contrôle de la permission create.", expected: "La cause permission est vérifiée." },
    ],
    result: "L'import peut être corrigé sans action risquée.",
  },
  {
    id: "HELP-ERR-005",
    version: 1,
    title: "Un webhook est refusé",
    description: "Comprendre un refus webhook sans contourner la politique SSRF.",
    roles: ["admin"],
    contexts: ["troubleshooting", "webhooks"],
    permissions: [{ object: "webhook", action: "administer" }],
    prerequisites: ["ADM-WEB-001"],
    tags: ["depannage", "webhook", "ssrf"],
    steps: [
      { title: "Lire le message", instruction: "Lire le message de refus affiché lors de la création ou dans les livraisons.", expected: "Le refus est identifié." },
      { title: "Contrôler l'URL", instruction: "Vérifier que l'URL est complète et utilise un schéma autorisé.", expected: "L'URL est syntaxiquement valide." },
      { title: "Respecter la politique", instruction: "Ne pas chercher de variante pour contourner la protection SSRF.", expected: "La sécurité reste appliquée." },
      { title: "Corriger la destination", instruction: "Utiliser une destination externe autorisée et maintenue.", expected: "Le webhook peut être recréé." },
    ],
    result: "Le webhook est corrigé dans le cadre de la politique de sécurité.",
  },
  {
    id: "HELP-ERR-006",
    version: 1,
    title: "Une modification ne semble pas enregistrée",
    description: "Vérifier une modification sans forcer les données.",
    roles: ["user", "admin"],
    contexts: ["troubleshooting", "crm"],
    prerequisites: ["COM-REC-001"],
    tags: ["depannage", "modification", "enregistrement"],
    steps: [
      { title: "Lire le message", instruction: "Lire le message affiché après l'action.", expected: "Succès ou erreur est connu." },
      { title: "Recharger la fiche", instruction: "Cliquer à nouveau sur la fiche dans la liste.", expected: "Les données serveur se rechargent." },
      { title: "Contrôler le JSON", instruction: "Si la modification concerne le JSON, vérifier que le JSON est valide.", expected: "La syntaxe est correcte." },
      { title: "Contrôler les droits", instruction: "Si le serveur refuse, demander le contrôle de la permission update.", expected: "La permission est vérifiée." },
    ],
    result: "Vous savez si la modification est enregistrée, refusée ou invalide.",
  },
];

export const helpCatalog = [
  ...commonProcedures,
  ...userProcedures,
  ...recordProcedures(),
  ...adminProcedures,
  ...troubleshootingProcedures,
];

export const helpCategories = [
  { id: "user", title: "Utilisateur", contexts: ["dashboard", "crm", "forms", "notifications"] },
  { id: "admin", title: "Administrateur", contexts: ["config", "automations", "webhooks", "rights"] },
  { id: "troubleshooting", title: "Dépannage", contexts: ["troubleshooting"] },
];