export const glossary = [
  { term: "Tenant", definition: "Périmètre logique d'isolation des données. Dans Clarity CRM, il correspond à l'organisation courante." },
  { term: "Organisation", definition: "Entité métier utilisatrice de Clarity CRM. Elle porte ses utilisateurs, équipes, configurations et données." },
  { term: "Rôle", definition: "Profil général de l'utilisateur dans un tenant : utilisateur ou administrateur." },
  { term: "Permission", definition: "Droit calculé côté serveur sur un objet, une action et un scope." },
  { term: "Scope", definition: "Périmètre d'une permission : personal pour vos ressources, team pour l'équipe, tenant pour toute l'organisation." },
  { term: "Équipe", definition: "Groupe d'utilisateurs servant au périmètre team et à la gouvernance des accès." },
  { term: "Objet métier", definition: "Type d'enregistrement CRM natif ou personnalisé dont les données passent par le moteur CRM générique." },
  { term: "Champ personnalisé", definition: "Champ déclaré sur un objet configurable et validé côté serveur : texte, texte long, nombre, devise, booléen, date, date/heure, liste, email, téléphone ou relation." },
  { term: "Pipeline", definition: "Suite ordonnée d'étapes rattachée à un type d'objet. Plusieurs pipelines actifs peuvent coexister pour un même objet." },
  { term: "Timeline", definition: "Historique d'activité rattaché à une fiche CRM." },
  { term: "Relation", definition: "Lien explicite entre deux fiches du même tenant, éventuellement contraint par une configuration source, cible et cardinalité." },
  { term: "Cardinalité", definition: "Nombre de liens admis de chaque côté d'une relation : un-à-un, un-à-plusieurs, plusieurs-à-un ou plusieurs-à-plusieurs." },
  { term: "Version de configuration", definition: "Instantané immuable créé à chaque modification ou restauration d'une configuration." },
  { term: "Automatisation", definition: "Règle déterministe configurée avec déclencheur, conditions et actions." },
  { term: "Webhook", definition: "Notification HTTP sortante ou entrante configurée et sécurisée par Clarity CRM." },
  { term: "Audit", definition: "Trace horodatée des actions importantes, réussites, refus et échecs." },
];
