export const glossary = [
  { term: "Tenant", definition: "Périmètre logique d'isolation des données. Dans Clarity CRM, il correspond à l'organisation courante." },
  { term: "Organisation", definition: "Entité métier utilisatrice de Clarity CRM. Elle porte ses utilisateurs, équipes, configurations et données." },
  { term: "Rôle", definition: "Profil général de l'utilisateur dans un tenant : utilisateur ou administrateur." },
  { term: "Permission", definition: "Droit calculé côté serveur sur un objet, une action et un scope." },
  { term: "Scope", definition: "Périmètre d'une permission : personal pour vos ressources, team pour l'équipe, tenant pour toute l'organisation." },
  { term: "Équipe", definition: "Groupe d'utilisateurs servant au périmètre team et à la gouvernance des accès." },
  { term: "Objet métier", definition: "Type d'enregistrement CRM : société, contact, lead, opportunité, tâche, rendez-vous, note, document, produit, service, devis, facture ou contrat." },
  { term: "Pipeline", definition: "Vue de progression des opportunités. Dans V1Console, il est consulté via le dashboard et l'objet Opportunité." },
  { term: "Timeline", definition: "Historique d'activité rattaché à une fiche CRM." },
  { term: "Relation", definition: "Lien explicite entre deux fiches du même tenant." },
  { term: "Automatisation", definition: "Règle déterministe configurée avec déclencheur, conditions et actions." },
  { term: "Webhook", definition: "Notification HTTP sortante ou entrante configurée et sécurisée par Clarity CRM." },
  { term: "Audit", definition: "Trace horodatée des actions importantes, réussites, refus et échecs." },
];